/**
 * The only place the site sorts or selects records.
 *
 * `src/data/*.json` is written by the Artemis Discord bot (see
 * `docs/data-contract.md`). The bot promises a sort order, but a hand edit can
 * break it, so every reader here re-sorts instead of trusting the file. Nothing
 * in this module reaches for `Date.now()` except where a caller passes today in.
 */

export interface RaceResult {
  id: string;
  date: string;
  event: string;
  track: string;
  series: string;
  class: string;
  position: number;
  entries?: number;
  drivers: string[];
  note?: string;
  /* Seed data, not a real race. Every consumer filters on this before
     publishing: the sitemap, the structured data, the feed and the
     production build guard. Declared here so the compiler enforces that
     rather than each caller reaching for a property the type denies. */
  _placeholder?: boolean;
}

export interface Driver {
  id: string;
  name: string;
  role: 'driver' | 'pitwall' | 'staff' | string;
  group: 'road' | 'oval' | 'crew' | string;
  number: string;
  country: string;
  focus: string;
  bio?: string;
  stats?: { irating?: number; licence?: string };
  socials?: Record<string, string>;
  active?: boolean;
  /** iRacing customer id. When present the nightly sync fills stats.json. */
  iracingId?: number;
  /** Seed data, not a real person. See the note on `RaceResult`. */
  _placeholder?: boolean;
}

export interface RaceEvent {
  id: string;
  name: string;
  track: string;
  start: string;
  /** Green flag, ISO 8601 UTC, on the `start` date. Optional. */
  startTime?: string;
  end?: string;
  classes: string[];
  status: 'planned' | 'confirmed' | 'done' | 'skipped' | string;
  note?: string;
  /** Seed data, not a real entry. See the note on `RaceResult`. */
  _placeholder?: boolean;
}

/** An open (or filled) seat, hand-edited in src/data/seats.json. */
export interface Seat {
  id: string;
  program: 'road' | 'oval' | 'crew' | string;
  role: string;
  requirements: string[];
  status: 'open' | 'filled' | string;
  note?: string;
  _placeholder?: boolean;
}

/* stats.json is generated by scripts/fetch-iracing.mjs and is optional in
   every direction: the file may be missing, a driver may have no entry, a
   category may be absent. Nothing here ever renders a label without a
   value. */
export interface DriverStats {
  iracingId?: number;
  irating?: Record<string, number>;
  safety?: Record<string, string>;
  recent?: {
    date: string;
    series: string;
    track?: string;
    car?: string;
    start: number;
    finish: number;
    sof?: number;
    incidents?: number;
  }[];
}

export interface StatsFile {
  updated?: string;
  source?: string;
  drivers?: Record<string, DriverStats>;
}

/* Results ----------------------------------------------------------- */

/** Contract order: date descending, then position ascending. */
export function sortResults(results: RaceResult[]): RaceResult[] {
  return [...results].sort(
    (a, b) => b.date.localeCompare(a.date) || a.position - b.position
  );
}

/** Home "Recent results" takes the first 6; the partners dossier the first 3. */
export function recentResults(results: RaceResult[], count: number): RaceResult[] {
  return sortResults(results).slice(0, count);
}

/**
 * Hero proof row: the best finish among the three newest races, so the first
 * screen is current rather than cherry-picked from the whole season.
 * Ties go to the newer race, which sortResults already puts first.
 */
export function heroProof(results: RaceResult[]): RaceResult | undefined {
  const newest = sortResults(results).slice(0, 3);
  if (!newest.length) return undefined;
  return newest.reduce((best, row) => (row.position < best.position ? row : best));
}

/** The most recent race a driver appears in, matched on `name`. */
export function latestFinish(
  results: RaceResult[],
  driverName: string
): RaceResult | undefined {
  return sortResults(results).find((row) => row.drivers.includes(driverName));
}

/** How many of these results were podiums. */
export function podiumCount(results: RaceResult[]): number {
  return results.filter((row) => row.position <= 3).length;
}

/** Distinct series, newest race first, for the partners season summary. */
export function seriesRun(results: RaceResult[]): string[] {
  return [...new Set(sortResults(results).map((row) => row.series))];
}

/* Drivers ----------------------------------------------------------- */

const GROUP_ORDER = ['road', 'oval', 'crew'];

/** Contract order: road, oval, crew; then car number ascending; crew by name. */
export function sortDrivers(drivers: Driver[]): Driver[] {
  return [...drivers].sort((a, b) => {
    const group = GROUP_ORDER.indexOf(a.group) - GROUP_ORDER.indexOf(b.group);
    if (group !== 0) return group;
    if (a.group === 'crew') return a.name.localeCompare(b.name);
    return Number(a.number || 0) - Number(b.number || 0) || a.name.localeCompare(b.name);
  });
}

/** `active: false` keeps a record in the file but off the site. */
export function activeDrivers(drivers: Driver[]): Driver[] {
  return sortDrivers(drivers).filter((driver) => driver.active !== false);
}

/** Home teaser: the first four active drivers (crew and staff excluded). */
export function featuredDrivers(drivers: Driver[], count: number): Driver[] {
  return activeDrivers(drivers)
    .filter((driver) => driver.role === 'driver')
    .slice(0, count);
}

export function driversInGroup(drivers: Driver[], group: string): Driver[] {
  return activeDrivers(drivers).filter((driver) => driver.group === group);
}

/* Events ------------------------------------------------------------ */

/** The event a visitor should see next: first upcoming, planned or confirmed. */
export function nextEvent(events: RaceEvent[], today: string): RaceEvent | undefined {
  return upcomingEvents(events, today)[0];
}

/** Every upcoming entry, so "next race" can also list what follows it. */
export function upcomingEvents(events: RaceEvent[], today: string): RaceEvent[] {
  return [...events]
    .filter((event) => event.status === 'planned' || event.status === 'confirmed')
    .filter((event) => (event.end ?? event.start) >= today)
    .sort((a, b) => a.start.localeCompare(b.start));
}

/** Fallback subtitle when nothing is scheduled: the last race actually run. */
export function lastCompletedEvent(events: RaceEvent[]): RaceEvent | undefined {
  return [...events]
    .filter((event) => event.status === 'done')
    .sort((a, b) => b.start.localeCompare(a.start))[0];
}

/**
 * The countdown target.
 *
 * With a `startTime` the answer is the green flag itself, to the minute, and
 * the countdown is exact. Without one it falls back to midnight on the start
 * date in the team's timezone (America/Chicago) expressed in UTC, which is
 * what every record carried before the contract gained the field.
 */
export function eventTarget(event: RaceEvent): string {
  return event.startTime ?? countdownTarget(event.start);
}

/**
 * Midnight on the start date in the team's timezone (America/Chicago),
 * expressed in UTC so the browser can subtract it from its own clock. US DST
 * runs from the second Sunday in March to the first Sunday in November, both
 * switching at 02:00 local, so a date's own midnight is still on the previous
 * offset on each of those two days.
 */
export function countdownTarget(startDate: string): string {
  const year = Number(startDate.slice(0, 4));
  const dstStart = nthSundayOfMonth(year, 3, 2);
  const dstEnd = nthSundayOfMonth(year, 11, 1);
  const daylight = startDate > dstStart && startDate <= dstEnd;
  return `${startDate}T0${daylight ? 5 : 6}:00:00Z`;
}

function nthSundayOfMonth(year: number, month: number, nth: number): string {
  const first = new Date(Date.UTC(year, month - 1, 1));
  const day = 1 + ((7 - first.getUTCDay()) % 7) + (nth - 1) * 7;
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

/* Seats -------------------------------------------------------------- */

/** The open seats, in the order the file lists them. */
export function openSeats(seats: Seat[]): Seat[] {
  return seats.filter((seat) => seat.status === 'open');
}

/* Driver statistics --------------------------------------------------- */

/**
 * iRacing keeps five licence categories; a driver's group decides which one
 * the site shows. A crew member has no racing category, so nothing renders
 * for them even if the sync wrote an entry.
 */
const STATS_CATEGORY: Record<string, string> = {
  road: 'sports_car',
  oval: 'oval',
};

export interface ResolvedStats {
  category: string;
  irating?: number;
  safety?: string;
  recent: NonNullable<DriverStats['recent']>;
}

/**
 * One driver's slice of stats.json, or undefined.
 *
 * Every step is optional on purpose: the file may not exist, the driver may
 * have no `iracingId`, the category may be missing, `recent` may be empty.
 * The rule the site follows is that a label is never rendered without a
 * value, so a partial entry renders only the parts that are real.
 */
export function driverStats(
  stats: StatsFile | undefined,
  driver: Driver
): ResolvedStats | undefined {
  const entry = stats?.drivers?.[driver.id];
  const category = STATS_CATEGORY[driver.group];
  if (!entry || !category) return undefined;

  const rawRating = entry.irating?.[category];
  const irating =
    typeof rawRating === 'number' && Number.isFinite(rawRating) && rawRating > 0
      ? Math.round(rawRating)
      : undefined;

  const rawSafety = entry.safety?.[category];
  const safety = typeof rawSafety === 'string' && rawSafety.trim() ? rawSafety : undefined;

  const recent = (Array.isArray(entry.recent) ? entry.recent : [])
    .filter((row) => row && typeof row.date === 'string')
    .slice(0, 3);

  if (irating === undefined && safety === undefined && recent.length === 0) return undefined;
  return { category, irating, safety, recent };
}

/* Standings ---------------------------------------------------------
   Points are NOT computed from results.json, and that is deliberate.
   League scoring is league-specific - drop weeks, bonus points for pole or
   laps led, split-dependent multipliers - so a table worked out here would
   disagree with the league's own table, and a standings sheet that is
   subtly wrong is worse than no standings sheet. results.json also has no
   season or round to compute over.

   So standings.json is written whole, by whoever has the real numbers: the
   Discord bot today, and a /data/league/season_standings call inside
   fetch-iracing.mjs later, once there is a league id to ask about. Both
   write the same shape, which is why the shape carries its own season
   metadata rather than borrowing any from elsewhere.
------------------------------------------------------------------- */

export interface Standing {
  position: number;
  driver: string;
  /**
   * Set when this row is one of ours, and it must match an id in
   * drivers.json. Present means the name links to their page and the row is
   * marked as the team's; absent means a rival. Listing rivals is what makes
   * this a championship table rather than a roster with points beside it.
   */
  driverId?: string;
  points: number;
  starts?: number;
  wins?: number;
  podiums?: number;
  /** Places gained (positive) or lost (negative) since the last round. */
  movement?: number;
  _placeholder?: boolean;
}

export interface StandingsFile {
  season?: string;
  series?: string;
  /** The league's own table, so the page can point at its source. */
  url?: string;
  updated?: string;
  rounds?: { run?: number; total?: number };
  standings?: Standing[];
}

/**
 * True when there is a real table to show.
 *
 * The page exists either way and renders an honest empty state when this is
 * false. It must never render a placeholder table: a made-up championship
 * is exactly the kind of claim the rest of this site refuses to make.
 */
export function hasStandings(file: StandingsFile | undefined): boolean {
  return Array.isArray(file?.standings) && file.standings.length > 0;
}

/** The table, by position. Sorted here so a hand-edited file still reads right. */
export function standingsRows(file: StandingsFile | undefined): Standing[] {
  return [...(file?.standings ?? [])].sort((a, b) => a.position - b.position);
}

/* A driver's own page ------------------------------------------------
   `driverStats` above answers "what does the roster row show": one
   category, three races, chosen by the driver's group. The page under
   /team/<id> is the place that shows everything the sync returned, so it
   gets its own reader rather than a flag on that one.
------------------------------------------------------------------- */

/** Display names for the categories iRacing reports. */
const CATEGORY_LABEL: Record<string, string> = {
  sports_car: 'Sports car',
  formula_car: 'Formula',
  oval: 'Oval',
  dirt_oval: 'Dirt oval',
  dirt_road: 'Dirt road',
  road: 'Road',
};

/* The order a racing person reads them in, not alphabetical. A category the
   sync returns that is not on this list still renders - it sorts to the end
   rather than disappearing, because a missing number is a bug the page
   should show rather than hide. */
const CATEGORY_ORDER = ['sports_car', 'formula_car', 'oval', 'dirt_oval', 'dirt_road', 'road'];

export interface CategoryRating {
  category: string;
  label: string;
  irating?: number;
  safety?: string;
}

export interface DriverProfile {
  /** Every category the sync returned a number or a licence for. */
  ratings: CategoryRating[];
  /** The full recent-races list, not the roster row's three. */
  recent: NonNullable<DriverStats['recent']>;
}

/**
 * Everything stats.json holds for one driver, for their own page.
 *
 * Same contract as `driverStats`: undefined when there is nothing real to
 * show, so the page can omit whole sections rather than render a heading
 * over an empty box. `stats.json` is not committed to the repository, so
 * undefined is the normal answer until the nightly sync has run.
 */
export function driverProfile(
  stats: StatsFile | undefined,
  driver: Driver
): DriverProfile | undefined {
  const entry = stats?.drivers?.[driver.id];
  if (!entry) return undefined;

  const keys = new Set([
    ...Object.keys(entry.irating ?? {}),
    ...Object.keys(entry.safety ?? {}),
  ]);

  const ratings = [...keys]
    .map((category): CategoryRating => {
      const rawRating = entry.irating?.[category];
      const rawSafety = entry.safety?.[category];
      return {
        category,
        label: CATEGORY_LABEL[category] ?? category.replace(/_/g, ' '),
        /* Same rule as `driverStats`: iRating is an integer, so 0 is a
           missing value rather than a real rating. */
        irating:
          typeof rawRating === 'number' && Number.isFinite(rawRating) && rawRating > 0
            ? Math.round(rawRating)
            : undefined,
        safety: typeof rawSafety === 'string' && rawSafety.trim() ? rawSafety : undefined,
      };
    })
    .filter((row) => row.irating !== undefined || row.safety !== undefined)
    .sort((a, b) => {
      const order = CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category);
      /* indexOf gives -1 for an unknown category, which would sort it to the
         front; push those to the end instead and break the tie by name. */
      if (CATEGORY_ORDER.includes(a.category) !== CATEGORY_ORDER.includes(b.category)) {
        return CATEGORY_ORDER.includes(a.category) ? -1 : 1;
      }
      return order || a.category.localeCompare(b.category);
    });

  const recent = (Array.isArray(entry.recent) ? entry.recent : []).filter(
    (row) => row && typeof row.date === 'string'
  );

  if (ratings.length === 0 && recent.length === 0) return undefined;
  return { ratings, recent };
}

/**
 * A driver's channels as [key, url] pairs, with the empty ones dropped.
 *
 * The bot writes `"socials": {"twitch": ""}` to clear a channel rather than
 * removing the key, so the filter is what keeps a link with no href off the
 * page. Shared by the roster row and the driver's own page so both agree on
 * what counts as a channel.
 */
export function socialsOf(driver: Driver): [string, string][] {
  return Object.entries(driver.socials ?? {}).filter(([, url]) => url);
}

/** Every team entry this driver appears in, newest first. Matched on `name`. */
export function resultsForDriver(results: RaceResult[], driverName: string): RaceResult[] {
  return sortResults(results).filter((row) => row.drivers.includes(driverName));
}

/**
 * Who gets a page under /team/<id>.
 *
 * Drivers only. A pitwall or staff record carries a name, a focus and a bio
 * and nothing else, all of which the roster row already shows in full - a
 * page for one would hold strictly less than the row that linked to it.
 */
export function hasOwnPage(driver: Driver): boolean {
  return driver.active !== false && driver.role === 'driver';
}

/** Today in the team's timezone, for build-time "is this race still ahead". */
export function todayInTeamZone(now: Date = new Date()): string {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Chicago',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(now);
}
