/**
 * Tests for src/lib/stats.js: the read-only summary of stats.json used by
 * /data status. stats.json is generated by a separate nightly job (see
 * docs/data-contract.md, version 1.2) and is never validated or written by
 * this bot, so these tests only cover reading it, tolerating it being
 * missing, and tolerating it being malformed.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createLocalStorage } from '../src/lib/storage-local.js';
import { STATS_FILE, readStatsSummary, summarizeStats } from '../src/lib/stats.js';

/**
 * Create a throwaway data directory and the local storage backend for it.
 * @param {string | null} statsContent written to stats.json, or omitted entirely when null
 * @returns {Promise<{ storage: object, cleanup: () => Promise<void> }>}
 */
async function makeStorage(statsContent) {
  const dir = await mkdtemp(path.join(tmpdir(), 'artemis-bot-stats-test-'));
  if (statsContent !== null) {
    await writeFile(path.join(dir, STATS_FILE), statsContent, 'utf8');
  }
  return {
    storage: createLocalStorage({ dataDir: dir }),
    cleanup: () => rm(dir, { recursive: true, force: true }),
  };
}

test('STATS_FILE is stats.json', () => {
  assert.equal(STATS_FILE, 'stats.json');
});

test('summarizeStats reads updated and counts the drivers', () => {
  const text = JSON.stringify({
    updated: '2026-09-14T09:00:12Z',
    source: 'iracing-data-api',
    drivers: { 'matthew-blackley': {}, 'nolan-walker': {} },
  });
  assert.deepEqual(summarizeStats(text), { updated: '2026-09-14T09:00:12Z', driverCount: 2 });
});

test('summarizeStats tolerates a missing updated or drivers key', () => {
  assert.deepEqual(summarizeStats('{}'), { updated: 'unknown', driverCount: 0 });
  assert.deepEqual(summarizeStats('{"updated":"2026-09-14T09:00:12Z"}'), {
    updated: '2026-09-14T09:00:12Z',
    driverCount: 0,
  });
});

test('summarizeStats refuses content that is not a JSON object', () => {
  assert.throws(() => summarizeStats('[]'), /must contain a JSON object/);
  assert.throws(() => summarizeStats('null'), /must contain a JSON object/);
  assert.throws(() => summarizeStats('not json'), /Unexpected token/);
});

test('readStatsSummary reports found: false when stats.json does not exist', async (t) => {
  const { storage, cleanup } = await makeStorage(null);
  t.after(cleanup);
  assert.deepEqual(await readStatsSummary(storage), { found: false, ok: false });
});

test('readStatsSummary reports ok: true with the file present and well formed', async (t) => {
  const { storage, cleanup } = await makeStorage(
    JSON.stringify({
      updated: '2026-09-14T09:00:12Z',
      drivers: { 'matthew-blackley': {}, 'nolan-walker': {}, 'ines-marchetti': {} },
    }),
  );
  t.after(cleanup);
  assert.deepEqual(await readStatsSummary(storage), {
    found: true,
    ok: true,
    updated: '2026-09-14T09:00:12Z',
    driverCount: 3,
  });
});

test('readStatsSummary reports found but not ok for malformed JSON, and never throws', async (t) => {
  const { storage, cleanup } = await makeStorage('{ not json at all');
  t.after(cleanup);
  const summary = await readStatsSummary(storage);
  assert.equal(summary.found, true);
  assert.equal(summary.ok, false);
  assert.equal(typeof summary.error, 'string');
});

test('readStatsSummary never validates or requires the file: an empty object is still ok', async (t) => {
  const { storage, cleanup } = await makeStorage('{}');
  t.after(cleanup);
  assert.deepEqual(await readStatsSummary(storage), { found: true, ok: true, updated: 'unknown', driverCount: 0 });
});
